

name: Build Docker image

on: [push]
#  push:
#    tags: testing-[1-9]+.[0-9]+.[0-9]+

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Find the version
        run: echo "RELEASE_VERSION=testing123" >> $GITHUB_ENV

      - name: Show the discovered version
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          echo $GITHUB_REF
          echo ${{ env.GITHUB_REF }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          build_args: VERSION=${{ env.RELEASE_VERSION }}
          no-cache: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/phplist-dev:${{ env.RELEASE_VERSION }}
